# =============================================================================
# Datenkrake Access Point - hostapd Konfiguration
# =============================================================================

# Interface und Treiber
interface=wlan0
driver=nl80211

# WLAN-Name und Kanal
ssid=Datenkrake
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0

# Authentifizierung
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=DatenkrakeAP
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP

# Ländercode (für korrekte Frequenz-Regulierung)
country_code=DE
ieee80211d=1
ieee80211n=1
